// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setting

import (
	"github.com/project-good-deal/chat-system/src/chat/adapter/in/web"
	"github.com/project-good-deal/chat-system/src/chat/adapter/out/chat_persistence"
	"github.com/project-good-deal/chat-system/src/chat/application/services/chat_service"
)

// Injectors from wire.go:

func InitializeChatController() *web.ChatController {
	chatRoomRepository := chat_persistence.NewChatRoomPersistenceAdapter()
	chatUseCase := chat_service.NewChatService(chatRoomRepository)
	chatController := web.NewChatController(chatUseCase)
	return chatController
}

func InitializeChatRoomController() *web.ChatRoomController {
	chatRoomRepository := chat_persistence.NewChatRoomPersistenceAdapter()
	chatRoomUseCase := chat_service.NewChatRoomService(chatRoomRepository)
	chatRoomController := web.NewChatRoomController(chatRoomUseCase)
	return chatRoomController
}
