package routers

import (
	"github.com/gin-gonic/gin"

	_ "github.com/project-good-deal/chat-system/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/project-good-deal/chat-system/src/setting"
)

// InitRouter initialize routing information
func InitRouter() *gin.Engine {
	r := gin.New()
	r.Use(gin.Logger())
	r.Use(gin.Recovery())
	
	chatController := setting.InitializeChatController()
	chatRoomController := setting.InitializeChatRoomController()

	api := r.Group("/api")
	{
		api.POST("/chat", chatController.CreateChat)
    api.POST("/chat-room", chatRoomController.CreateChatRoom)
    api.GET("/chat-room", chatRoomController.GetChatRoomByUserId)
	}

	return r
}
