package main

import (
	"net/http"
	"log"
	"fmt"

	"github.com/gin-gonic/gin"

	_ "github.com/project-good-deal/chat-system/docs" // docs is generated by Swag CLI, you have to import it.
	// "github.com/project-good-deal/chat-system/src/common/setting"
	"github.com/project-good-deal/chat-system/src/routers"
	// "github.com/good-deal/chat-system/src/chat/adapter/in/web"
)



func init() {
}

// @title Golang Gin API
// @version 1.0
// @description An example of gin
func main() {
	gin.SetMode(gin.DebugMode)

	routersInit := routers.InitRouter()
	endPoint := fmt.Sprintf(":%d", 8080)
	maxHeaderBytes := 1 << 20

	server := &http.Server{
		Addr:           endPoint,
		Handler:        routersInit,
		MaxHeaderBytes: maxHeaderBytes,
	}

	log.Printf("[info] start http server listening %s", endPoint)

	server.ListenAndServe()

	// If you want Graceful Restart, you need a Unix system and download github.com/fvbock/endless
	//endless.DefaultReadTimeOut = readTimeout
	//endless.DefaultWriteTimeOut = writeTimeout
	//endless.DefaultMaxHeaderBytes = maxHeaderBytes
	//server := endless.NewServer(endPoint, routersInit)
	//server.BeforeBegin = func(add string) {
	//	log.Printf("Actual pid is %d", syscall.Getpid())
	//}
	//
	//err := server.ListenAndServe()
	//if err != nil {
	//	log.Printf("Server err: %v", err)
	//}
}
